"""JK Fenner Warehouse Operations Scenario Simulation — Streamlit app."""
from pathlib import Path
import tempfile

import pandas as pd
import streamlit as st
from shapely.geometry import Point, box as shapely_box

from core.pipeline import run_pipeline, prepare_cad
from core.visualization_engine import plot_cad_geometry, plot_layout, plot_slot_allocation
from core.scenario_engine import prepare_movement, build_scenario_table, rank_skus, allocate_slots

st.set_page_config(page_title="JK Fenner Warehouse Operations Scenario Simulation", page_icon="🏭", layout="wide")

st.markdown("""
<style>
.block-container{padding-top:1.2rem;padding-bottom:2rem}
.hero h1{margin:0;font-size:2.1rem}
.hero p{margin:.2rem 0 1rem;color:#6b7280}
.note{font-size:.82rem;color:#6b7280}
</style>
""", unsafe_allow_html=True)

st.markdown(
    '<div class="hero"><h1>🏭 JK Fenner Warehouse Operations Scenario Simulation</h1>'
    '<p>Model 1 establishes feasible physical slots. Model 2 tests how those same slots can be allocated using observed SKU movement.</p></div>',
    unsafe_allow_html=True,
)


def save_upload(upload):
    suffix = Path(upload.name).suffix.lower()
    f = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
    f.write(upload.getbuffer())
    f.close()
    return f.name


def reset_results():
    for key in ("result", "scenario", "cad_data", "cad_key", "selected_door", "door_x", "door_y", "door_reference"):
        st.session_state.pop(key, None)


def operating_door(cad):
    wh = cad["warehouse"]
    minx, miny, maxx, maxy = wh.bounds
    doors = cad.get("doors", [])
    st.markdown("#### Operating / custom door")
    if doors:
        labels = [f"CAD Door {i}: ({d['x']:.2f}, {d['y']:.2f})" for i, d in enumerate(doors, 1)]
        choice = st.selectbox("Reference door", labels, key="door_reference")
        ref = doors[labels.index(choice)]
        dx, dy = float(ref["x"]), float(ref["y"])
    else:
        dx, dy = float(wh.centroid.x), float(wh.centroid.y)
        st.warning("No CAD door detected. Enter the validated operating-door coordinates.")
    c1, c2 = st.columns(2)
    with c1:
        x = st.number_input("Custom door X (m)", float(minx), float(maxx), float(st.session_state.get("door_x", dx)), 0.1, key="door_x")
    with c2:
        y = st.number_input("Custom door Y (m)", float(miny), float(maxy), float(st.session_state.get("door_y", dy)), 0.1, key="door_y")
    st.caption(f"Model input: X = {x:.3f} m · Y = {y:.3f} m")
    return Point(x, y)


def analysis_region(warehouse, mode, x0=0.0, y0=0.0, x1=0.0, y1=0.0):
    """Create a selectable analysis area, always clipped to the CAD warehouse."""
    minx, miny, maxx, maxy = warehouse.bounds
    if mode == "Whole warehouse":
        return warehouse
    if mode == "Left half":
        return warehouse.intersection(shapely_box(minx, miny, (minx + maxx) / 2, maxy))
    if mode == "Right half":
        return warehouse.intersection(shapely_box((minx + maxx) / 2, miny, maxx, maxy))
    if mode == "Lower half":
        return warehouse.intersection(shapely_box(minx, miny, maxx, (miny + maxy) / 2))
    if mode == "Upper half":
        return warehouse.intersection(shapely_box(minx, (miny + maxy) / 2, maxx, maxy))
    return warehouse.intersection(shapely_box(x0, y0, x1, y1))


with st.sidebar:
    st.header("Project inputs")
    st.caption("Model 2 uses the exact feasible slots generated by Model 1 for the selected area.")
    cad_file = st.file_uploader("1 · Warehouse CAD", ["dxf"], key="cad")
    demand_file = st.file_uploader("2 · Daily demand", ["xlsx", "csv"], key="demand")
    mto_file = st.file_uploader("3 · Raw MTO transactions", ["xlsx", "csv"], key="mto")
    mta_file = st.file_uploader("4 · Raw MTA transactions (optional)", ["xlsx", "csv"], key="mta")

    st.divider()
    st.subheader("Model 1 · Physical settings")
    pallet_width = st.number_input("Pallet width (m)", 0.1, 5.0, 1.20, 0.05)
    pallet_depth = st.number_input("Pallet depth (m)", 0.1, 5.0, 1.00, 0.05)
    occupancy = st.slider("Planning occupancy (%)", 50, 85, 65)
    with st.expander("Advanced physical constraints"):
        wall_clearance = st.number_input("Wall clearance (m)", 0.0, 5.0, 0.25, 0.05)
        main_aisle = st.number_input("Main aisle (m)", 0.5, 10.0, 4.0, 0.25)
        cross_aisle = st.number_input("Cross aisle (m)", 0.0, 10.0, 2.0, 0.25)
        turning_diameter = st.number_input("Turning diameter (m)", 0.0, 20.0, 7.0, 0.25)
        forklift_speed = st.number_input("Forklift speed (m/s)", 0.1, 10.0, 2.5, 0.1)
        handling_time = st.number_input("Handling time (sec/pallet)", 0.0, 600.0, 0.0, 5.0)

    st.subheader("Model 2 · Scenario settings")
    area_mode = st.selectbox("Analysis area", ["Whole warehouse", "Left half", "Right half", "Lower half", "Upper half", "Custom rectangle"])
    if area_mode == "Custom rectangle" and "cad_data" in st.session_state:
        wh = st.session_state.cad_data["warehouse"]
        mnx, mny, mxx, mxy = wh.bounds
        x0 = st.number_input("Area X-min", float(mnx), float(mxx), float(mnx), 0.1)
        x1 = st.number_input("Area X-max", float(mnx), float(mxx), float(mxx), 0.1)
        y0 = st.number_input("Area Y-min", float(mny), float(mxy), float(mny), 0.1)
        y1 = st.number_input("Area Y-max", float(mny), float(mxy), float(mxy), 0.1)
    else:
        x0 = y0 = 0.0
        x1 = y1 = 0.0
    strategy = st.selectbox("Allocation strategy", ["Frequency priority", "Volume priority", "Frequency × volume"])
    belts_per_slot = st.number_input(
        "Scenario conversion: belts represented by one pallet slot",
        min_value=1.0, max_value=100000.0, value=1000.0, step=50.0,
        help="Explicit scenario parameter used only to convert observed movement quantity into slot equivalents. It is not an observed inventory balance. Replace with a validated warehouse value when available."
    )
    run_physical = st.button("▶ Run Model 1", type="primary", use_container_width=True)
    run_scenario = st.button("▶ Run Model 2 Scenario", use_container_width=True)
    if st.button("↺ Reset", use_container_width=True):
        reset_results(); st.rerun()

if cad_file:
    key = f"{cad_file.name}:{cad_file.size}"
    if st.session_state.get("cad_key") != key:
        try:
            st.session_state.cad_path = save_upload(cad_file)
            st.session_state.cad_data = prepare_cad(st.session_state.cad_path)
            st.session_state.cad_key = key
            for k in ("door_x", "door_y", "door_reference", "selected_door"):
                st.session_state.pop(k, None)
        except Exception as exc:
            st.error(f"CAD could not be read: {exc}"); st.stop()

if "cad_data" in st.session_state:
    cad = st.session_state.cad_data
    with st.expander("CAD review & operating door", expanded=True):
        a, b, c = st.columns(3)
        a.metric("Warehouse area", f"{cad['warehouse'].area:,.1f} m²")
        b.metric("CAD doors", len(cad.get("doors", [])))
        c.metric("Obstacles", len(cad.get("obstacles", [])))
        st.pyplot(plot_cad_geometry(cad), use_container_width=True)
        st.session_state.selected_door = operating_door(cad)

if run_physical:
    if "cad_path" not in st.session_state or not demand_file:
        st.error("Upload CAD + Daily demand first."); st.stop()
    if "selected_door" not in st.session_state:
        st.error("Set the operating/custom door below the CAD drawing."); st.stop()
    try:
        door = st.session_state.selected_door
        with st.spinner("Running Model 1 physical scenario…"):
            result = run_pipeline(
                st.session_state.cad_path, save_upload(demand_file),
                manual_door_xy=(door.x, door.y),
                pallet_width_m=pallet_width, pallet_depth_m=pallet_depth,
                wall_clearance_m=wall_clearance, main_aisle_m=main_aisle,
                cross_aisle_m=cross_aisle, turning_diameter_m=turning_diameter,
                target_occupancy_pct=occupancy, forklift_speed_mps=forklift_speed,
                handling_time_sec_per_pallet=handling_time,
            )
        result["config"] = {
            "pallet_width_m": pallet_width, "pallet_depth_m": pallet_depth,
            "wall_clearance_m": wall_clearance, "main_aisle_m": main_aisle,
            "cross_aisle_m": cross_aisle, "turning_diameter_m": turning_diameter,
            "target_occupancy_pct": occupancy, "forklift_speed_mps": forklift_speed,
            "handling_time_sec_per_pallet": handling_time,
            "operating_door_x_m": door.x, "operating_door_y_m": door.y,
        }
        st.session_state.result = result
        st.success("Model 1 completed. Its generated slots are now available to Model 2.")
    except Exception as exc:
        st.error(f"Model 1 failed: {exc}"); st.stop()

if run_scenario:
    if "result" not in st.session_state:
        st.error("Run Model 1 first so Model 2 can use its generated slots."); st.stop()
    if not mto_file:
        st.error("Upload the raw MTO transaction file first."); st.stop()
    try:
        r = st.session_state.result
        region = analysis_region(r["warehouse"], area_mode, x0, y0, x1, y1)
        if region.is_empty or region.area <= 0:
            st.error("Selected analysis area is empty. Adjust the area selection."); st.stop()
        slot_df = r["slot_df"].copy()
        slot_df = slot_df[slot_df.apply(lambda row: region.covers(Point(row["X_M"], row["Y_M"])), axis=1)].copy()
        slot_df = slot_df.sort_values("DISTANCE_FROM_DOOR_M").reset_index(drop=True)
        if slot_df.empty:
            st.error("No Model 1-generated slots fall inside the selected area."); st.stop()
        with st.spinner("Preparing SKU movement and allocating Model 1 slots…"):
            sku, mto_clean, mta_clean = prepare_movement(save_upload(mto_file), save_upload(mta_file) if mta_file else None)
            scenario_table, allocations = build_scenario_table(sku, slot_df, belts_per_slot)
            selected_rank = rank_skus(sku, strategy)
            selected_allocation, selected_summary = allocate_slots(selected_rank, slot_df, belts_per_slot)
        st.session_state.scenario = {
            "sku": sku, "mto": mto_clean, "mta": mta_clean,
            "region": region, "slot_df": slot_df,
            "strategy": strategy, "belts_per_slot": belts_per_slot,
            "scenario_table": scenario_table, "allocations": allocations,
            "allocation": selected_allocation, "summary": selected_summary,
        }
        st.success(f"Model 2 completed using {len(slot_df):,} Model 1-generated slots in the selected area.")
    except Exception as exc:
        st.error(f"Model 2 scenario failed: {exc}"); st.stop()

if "result" not in st.session_state and "scenario" not in st.session_state:
    st.info("Upload the inputs and run Model 1 first. Model 2 uses Model 1's generated slots.")
    st.stop()

result = st.session_state.get("result")
scenario = st.session_state.get("scenario")
tabs = st.tabs(["Overview", "Model 1 · Physical", "Model 2 · Slot Scenario", "Decision", "Downloads"])

with tabs[0]:
    st.markdown("### Executive overview")
    if result:
        cap, sim, dm = result["capacity"], result["simulation_summary"], result["demand_metrics"]
        k = st.columns(5)
        k[0].metric("Realistic capacity", f"{cap['realistic_capacity']:,}")
        k[1].metric("Planning capacity", f"{cap['planning_capacity']:,.0f}")
        k[2].metric("Average demand", f"{dm['average_daily_demand']:.1f}")
        k[3].metric("Peak demand", f"{dm['peak_demand']:.0f}")
        k[4].metric("Overflow days", f"{sim['overflow_days']}")
    if scenario:
        s = scenario["summary"]
        k = st.columns(5)
        k[0].metric("Selected area slots", f"{s['total_slots']:,}")
        k[1].metric("Allocated slots", f"{s['allocated_slots']:,}")
        k[2].metric("Slot utilization", f"{s['slot_utilization_pct']:.1f}%")
        k[3].metric("Movement coverage", f"{s['movement_coverage_pct']:.1f}%")
        k[4].metric("Overflow slot equivalents", f"{s['overflow_slot_equivalents']:,}")

with tabs[1]:
    if not result:
        st.info("Run Model 1.")
    else:
        r = result; cap = r["capacity"]
        st.markdown("### Model 1 · Physical Warehouse Scenario")
        k = st.columns(4)
        k[0].metric("Theoretical capacity", f"{cap['theoretical_capacity']:,}")
        k[1].metric("Realistic capacity", f"{cap['realistic_capacity']:,}")
        k[2].metric("Planning capacity", f"{cap['planning_capacity']:,.0f}")
        k[3].metric("Average door distance", f"{r['winner']['avg_distance_m']:.2f} m")
        st.pyplot(plot_layout(r["warehouse"], r["storage_region"], r["slots"], r["door"], r["winner"]["layout"]["main_aisle"], r["winner"]["layout"]["turning_circle"], r["obstacles"], title="Model 1 · Generated Feasible Pallet Slots"), use_container_width=True)
        st.dataframe(r["slot_df"], use_container_width=True, hide_index=True)

with tabs[2]:
    if not scenario:
        st.info("Run Model 2 Scenario after Model 1.")
    else:
        s = scenario["summary"]
        st.markdown("### Model 2 · SKU Slot-Allocation Scenario")
        st.caption("The physical slots are not regenerated here. They are filtered directly from Model 1's generated slot master for the selected analysis area.")
        k = st.columns(5)
        k[0].metric("Selected area", f"{scenario['region'].area:,.1f} m²")
        k[1].metric("Available slots", f"{s['total_slots']:,}")
        k[2].metric("Allocated", f"{s['allocated_slots']:,}")
        k[3].metric("Movement covered", f"{s['movement_coverage_pct']:.1f}%")
        k[4].metric("Overflow equivalents", f"{s['overflow_slot_equivalents']:,}")
        st.markdown(f"#### Selected strategy: **{scenario['strategy']}**")
        st.pyplot(plot_slot_allocation(result["warehouse"], scenario["region"], result["slots"], scenario["allocation"], result["door"], title=f"Model 2 · {scenario['strategy']} · Slot-by-Slot Allocation"), use_container_width=True)
        st.markdown("#### Scenario comparison")
        st.dataframe(scenario["scenario_table"], use_container_width=True, hide_index=True)
        st.markdown("#### Slot-by-slot allocation sequence")
        st.dataframe(scenario["allocation"], use_container_width=True, hide_index=True)
        st.markdown("#### SKU movement profile")
        st.dataframe(scenario["sku"].head(100), use_container_width=True, hide_index=True)

with tabs[3]:
    st.markdown("### Decision")
    if result:
        cap = result["capacity"]
        st.write(f"**Model 1:** the selected physical configuration produces **{cap['realistic_capacity']:,} feasible slots** and **{cap['planning_capacity']:,.0f} planning slots** under the chosen occupancy rule.")
    if scenario:
        st.write(f"**Model 2:** the selected area contains **{scenario['summary']['total_slots']:,} Model 1-generated slots**. Under **{scenario['strategy']}**, the simulation allocates those fixed slots sequentially according to observed SKU movement characteristics.")
        st.info("This is an operations scenario simulation, not a claim that the selected SKU allocation is the current physical inventory arrangement. The belts-per-slot value is an explicit scenario conversion parameter and should be replaced with a validated warehouse capacity value when available.")

with tabs[4]:
    st.markdown("### Downloads")
    if result:
        st.download_button("Download Model 1 slot master", result["slot_df"].to_csv(index=False).encode(), "model1_slot_master.csv", "text/csv", use_container_width=True)
        st.download_button("Download Model 1 daily results", result["daily_df"].to_csv(index=False).encode(), "model1_daily_simulation.csv", "text/csv", use_container_width=True)
    if scenario:
        st.download_button("Download SKU movement master", scenario["sku"].to_csv(index=False).encode(), "model2_sku_movement_master.csv", "text/csv", use_container_width=True)
        st.download_button("Download scenario comparison", scenario["scenario_table"].to_csv(index=False).encode(), "model2_scenario_comparison.csv", "text/csv", use_container_width=True)
        st.download_button("Download selected slot allocation", scenario["allocation"].to_csv(index=False).encode(), "model2_slot_allocation.csv", "text/csv", use_container_width=True)
        st.download_button("Download selected-area slot master", scenario["slot_df"].to_csv(index=False).encode(), "model2_selected_area_slots.csv", "text/csv", use_container_width=True)

st.divider()
st.caption("JK Fenner Warehouse Operations Scenario Simulation · Model 1 = physical feasibility · Model 2 = SKU slot allocation")
