"""SKU movement and slot-allocation scenario engine.

Model 2 is an Operations Scenario Simulation. It consumes the feasible pallet
slots generated by Model 1 and tests alternative SKU allocation priorities.
"""
from pathlib import Path
import math
import numpy as np
import pandas as pd


def load_table(path):
    path = Path(path)
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    if path.suffix.lower() in {".xlsx", ".xls"}:
        xl = pd.ExcelFile(path)
        for sheet in xl.sheet_names:
            df = pd.read_excel(path, sheet_name=sheet)
            if not df.empty:
                return df
    raise ValueError("File must be CSV or Excel and contain a non-empty sheet.")


def _find_col(df, names, required=True):
    lookup = {str(c).strip().upper(): c for c in df.columns}
    for name in names:
        if name.upper() in lookup:
            return lookup[name.upper()]
    if required:
        raise ValueError(f"Could not find any of columns: {names}")
    return None


def prepare_movement(mto_path, mta_path=None):
    """Clean raw MTO/MTA files and build an SKU movement master."""
    mto = load_table(mto_path).copy()
    sku_col = _find_col(mto, ["ITEM_SIZE", "BELT_SIZE", "SKU", "LINE_ITEM_SIZE_ID"])
    qty_col = _find_col(mto, ["NO_OF_BELTS", "BELTS", "QUANTITY", "QTY"])
    date_col = _find_col(mto, ["DATE", "PACKING_DATE", "INVOICE_DATE"], required=False)
    inv_col = _find_col(mto, ["INVOICE_ID", "INVOICE", "DOCUMENT_NO"], required=False)
    mto = mto.rename(columns={sku_col: "ITEM_SIZE", qty_col: "BELTS"})
    mto["ITEM_SIZE"] = mto["ITEM_SIZE"].astype("string").str.strip()
    mto["BELTS"] = pd.to_numeric(mto["BELTS"], errors="coerce")
    mto["DATE"] = pd.to_datetime(mto[date_col], errors="coerce", dayfirst=True) if date_col else pd.NaT
    mto["INVOICE_ID"] = mto[inv_col].astype("string") if inv_col else pd.NA
    mto = mto.drop_duplicates().copy()
    mto = mto[mto["ITEM_SIZE"].notna() & mto["BELTS"].notna() & (mto["BELTS"] > 0)].copy()

    mta = pd.DataFrame(columns=["ITEM_SIZE", "BELTS", "DATE", "INVOICE_ID"])
    if mta_path:
        raw = load_table(mta_path).copy()
        sku_col = _find_col(raw, ["ITEM_SIZE", "BELT_SIZE", "SKU", "LINE_ITEM_SIZE_ID"])
        qty_col = _find_col(raw, ["NO_OF_BELTS", "BELTS", "QUANTITY", "QTY"])
        date_col = _find_col(raw, ["DATE", "PACKING_DATE", "INVOICE_DATE"], required=False)
        inv_col = _find_col(raw, ["INVOICE_ID", "INVOICE", "DOCUMENT_NO"], required=False)
        raw = raw.rename(columns={sku_col: "ITEM_SIZE", qty_col: "BELTS"})
        raw["ITEM_SIZE"] = raw["ITEM_SIZE"].astype("string").str.strip()
        raw["BELTS"] = pd.to_numeric(raw["BELTS"], errors="coerce")
        raw["DATE"] = pd.to_datetime(raw[date_col], errors="coerce", dayfirst=True) if date_col else pd.NaT
        raw["INVOICE_ID"] = raw[inv_col].astype("string") if inv_col else pd.NA
        raw = raw.drop_duplicates().copy()
        total_mask = raw["ITEM_SIZE"].astype("string").str.contains("grand total|^total$", case=False, na=False)
        raw = raw[~total_mask]
        mta = raw[raw["ITEM_SIZE"].notna() & raw["BELTS"].notna() & (raw["BELTS"] > 0)][["ITEM_SIZE", "BELTS", "DATE", "INVOICE_ID"]].copy()

    sku = mto.groupby("ITEM_SIZE", as_index=False).agg(
        MTO_BELTS=("BELTS", "sum"), MTO_LINES=("ITEM_SIZE", "size"),
        MTO_INVOICES=("INVOICE_ID", "nunique"), ACTIVE_DAYS=("DATE", "nunique"),
        ACTIVE_MONTHS=("DATE", lambda x: x.dt.to_period("M").nunique()),
        AVG_BELTS_PER_LINE=("BELTS", "mean"), MAX_BELTS_PER_LINE=("BELTS", "max"),
    )
    if not mta.empty:
        mta_sku = mta.groupby("ITEM_SIZE", as_index=False).agg(
            MTA_BELTS=("BELTS", "sum"), MTA_LINES=("ITEM_SIZE", "size"),
            MTA_INVOICES=("INVOICE_ID", "nunique"), MTA_ACTIVE_DAYS=("DATE", "nunique"),
        )
        sku = sku.merge(mta_sku, on="ITEM_SIZE", how="outer")
    else:
        sku["MTA_BELTS"] = 0.0; sku["MTA_LINES"] = 0; sku["MTA_INVOICES"] = 0; sku["MTA_ACTIVE_DAYS"] = 0
    numeric = [c for c in sku.columns if c != "ITEM_SIZE"]
    sku[numeric] = sku[numeric].fillna(0)
    sku["TOTAL_MTO_MTA_BELTS"] = sku["MTO_BELTS"] + sku["MTA_BELTS"]
    sku["TOTAL_LINES"] = sku["MTO_LINES"] + sku["MTA_LINES"]
    sku["COMBINED_ACTIVE_DAYS"] = sku[["ACTIVE_DAYS", "MTA_ACTIVE_DAYS"]].max(axis=1)
    sku["MOVEMENT_SHARE_PCT"] = sku["MTO_BELTS"] / max(float(sku["MTO_BELTS"].sum()), 1) * 100
    sku["FREQUENCY_SCORE"] = sku["ACTIVE_DAYS"]
    sku["FREQUENCY_INDEX"] = sku["FREQUENCY_SCORE"] / max(float(sku["FREQUENCY_SCORE"].max()), 1) * 100
    volume_median = sku["MTO_BELTS"].median()
    frequency_median = sku["FREQUENCY_SCORE"].median()
    sku["VOLUME_CLASS"] = np.where(sku["MTO_BELTS"] >= volume_median, "High Volume", "Low Volume")
    sku["FREQUENCY_CLASS"] = np.where(sku["FREQUENCY_SCORE"] >= frequency_median, "Recurring", "Less Recurring")
    sku["MOVEMENT_SEGMENT"] = sku["FREQUENCY_CLASS"] + " / " + sku["VOLUME_CLASS"]
    sku = sku.sort_values(["MTO_BELTS", "FREQUENCY_SCORE"], ascending=False).reset_index(drop=True)
    sku["VOLUME_RANK"] = np.arange(1, len(sku) + 1)
    freq_order = sku.sort_values(["FREQUENCY_SCORE", "MTO_BELTS"], ascending=False).index
    freq_map = {idx: i + 1 for i, idx in enumerate(freq_order)}
    sku["FREQUENCY_RANK"] = [freq_map[i] for i in sku.index]
    sku["CUMULATIVE_MOVEMENT_SHARE_PCT"] = sku["MTO_BELTS"].cumsum() / max(float(sku["MTO_BELTS"].sum()), 1) * 100
    return sku, mto, mta


def rank_skus(sku, strategy):
    out = sku.copy()
    if strategy == "Frequency priority":
        out["STRATEGY_SCORE"] = out["FREQUENCY_SCORE"]
    elif strategy == "Volume priority":
        out["STRATEGY_SCORE"] = out["MTO_BELTS"]
    elif strategy == "Frequency × volume":
        f = out["FREQUENCY_SCORE"] / max(float(out["FREQUENCY_SCORE"].max()), 1)
        v = out["MTO_BELTS"] / max(float(out["MTO_BELTS"].max()), 1)
        out["STRATEGY_SCORE"] = np.sqrt(f * v)
    else:
        raise ValueError(f"Unknown strategy: {strategy}")
    return out.sort_values(["STRATEGY_SCORE", "MTO_BELTS", "FREQUENCY_SCORE"], ascending=False).reset_index(drop=True)


def allocate_slots(sku_ranked, slot_df, belts_per_slot):
    """Sequentially allocate the fixed Model 1 slot master to ranked SKUs."""
    if belts_per_slot <= 0:
        raise ValueError("Belts per slot must be greater than zero.")
    slots = slot_df.reset_index(drop=True)
    if slots.empty:
        raise ValueError("No Model 1 slots are available in the selected area.")
    rows = []
    slot_pos = 0
    total_slots = len(slots)
    cumulative_required = 0
    for rank, row in sku_ranked.iterrows():
        required = max(int(math.ceil(float(row["MTO_BELTS"]) / belts_per_slot)), 1)
        for local in range(required):
            base = {
                "ALLOCATION_SEQUENCE": len(rows) + 1,
                "ITEM_SIZE": row["ITEM_SIZE"], "SKU_RANK": rank + 1,
                "STRATEGY_SCORE": row["STRATEGY_SCORE"],
                "SLOTS_REQUIRED_FOR_SKU": required, "SLOT_WITHIN_SKU": local + 1,
            }
            if slot_pos < total_slots:
                s = slots.iloc[slot_pos]
                base.update({"SLOT_ID": s["SLOT_ID"], "STATUS": "ALLOCATED",
                             "X_M": s["X_M"], "Y_M": s["Y_M"],
                             "DISTANCE_FROM_DOOR_M": s["DISTANCE_FROM_DOOR_M"]})
                slot_pos += 1
            else:
                base.update({"SLOT_ID": None, "STATUS": "OVERFLOW",
                             "X_M": np.nan, "Y_M": np.nan, "DISTANCE_FROM_DOOR_M": np.nan})
            rows.append(base)
        cumulative_required += required
    allocation = pd.DataFrame(rows)
    allocated = allocation[allocation["STATUS"] == "ALLOCATED"]
    overflow = allocation[allocation["STATUS"] == "OVERFLOW"]

    cumulative = 0
    fully_covered = []
    for _, row in sku_ranked.iterrows():
        req = max(int(math.ceil(float(row["MTO_BELTS"]) / belts_per_slot)), 1)
        if cumulative + req <= total_slots:
            fully_covered.append(row["ITEM_SIZE"])
            cumulative += req
        else:
            break
    covered_belts = float(sku_ranked[sku_ranked["ITEM_SIZE"].isin(fully_covered)]["MTO_BELTS"].sum())
    overflow_skus = set(overflow["ITEM_SIZE"].dropna())
    overflow_belts = float(sku_ranked[sku_ranked["ITEM_SIZE"].isin(overflow_skus)]["MTO_BELTS"].sum()) if overflow_skus else 0.0
    summary = {
        "total_slots": total_slots,
        "allocated_slots": len(allocated),
        "empty_slots": total_slots - len(allocated),
        "overflow_slot_equivalents": len(overflow),
        "fully_covered_skus": len(fully_covered),
        "movement_coverage_pct": covered_belts / max(float(sku_ranked["MTO_BELTS"].sum()), 1) * 100,
        "slot_utilization_pct": len(allocated) / total_slots * 100,
        "overflow_belts_equivalent": overflow_belts,
    }
    return allocation, summary


def build_scenario_table(sku, slot_df, belts_per_slot):
    results, allocations = [], {}
    for strategy in ["Frequency priority", "Volume priority", "Frequency × volume"]:
        ranked = rank_skus(sku, strategy)
        allocation, summary = allocate_slots(ranked, slot_df, belts_per_slot)
        allocations[strategy] = allocation
        results.append({"STRATEGY": strategy, **summary})
    return pd.DataFrame(results), allocations
